/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as ShopsShopSlugRouteImport } from './routes/shops.$shopSlug'
import { Route as AuthenticatedManageShopIdRouteImport } from './routes/_authenticated/manage.$shopId'
import { Route as ApiPublicSyncPlacesRouteImport } from './routes/api/public/sync-places'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShopsShopSlugRoute = ShopsShopSlugRouteImport.update({
  id: '/shops/$shopSlug',
  path: '/shops/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManageShopIdRoute =
  AuthenticatedManageShopIdRouteImport.update({
    id: '/manage/$shopId',
    path: '/manage/$shopId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSyncPlacesRoute = ApiPublicSyncPlacesRouteImport.update({
  id: '/api/public/sync-places',
  path: '/api/public/sync-places',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/owners': typeof OwnersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRoute
  '/manage/$shopId': typeof AuthenticatedManageShopIdRoute
  '/api/public/sync-places': typeof ApiPublicSyncPlacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/owners': typeof OwnersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRoute
  '/manage/$shopId': typeof AuthenticatedManageShopIdRoute
  '/api/public/sync-places': typeof ApiPublicSyncPlacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/owners': typeof OwnersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRoute
  '/_authenticated/manage/$shopId': typeof AuthenticatedManageShopIdRoute
  '/api/public/sync-places': typeof ApiPublicSyncPlacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guide'
    | '/owners'
    | '/admin'
    | '/claims'
    | '/owner'
    | '/submit'
    | '/shops/$shopSlug'
    | '/manage/$shopId'
    | '/api/public/sync-places'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guide'
    | '/owners'
    | '/admin'
    | '/claims'
    | '/owner'
    | '/submit'
    | '/shops/$shopSlug'
    | '/manage/$shopId'
    | '/api/public/sync-places'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/guide'
    | '/owners'
    | '/_authenticated/admin'
    | '/_authenticated/claims'
    | '/_authenticated/owner'
    | '/_authenticated/submit'
    | '/shops/$shopSlug'
    | '/_authenticated/manage/$shopId'
    | '/api/public/sync-places'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuideRoute: typeof GuideRoute
  OwnersRoute: typeof OwnersRoute
  ShopsShopSlugRoute: typeof ShopsShopSlugRoute
  ApiPublicSyncPlacesRoute: typeof ApiPublicSyncPlacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/shops/$shopSlug': {
      id: '/shops/$shopSlug'
      path: '/shops/$shopSlug'
      fullPath: '/shops/$shopSlug'
      preLoaderRoute: typeof ShopsShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manage/$shopId': {
      id: '/_authenticated/manage/$shopId'
      path: '/manage/$shopId'
      fullPath: '/manage/$shopId'
      preLoaderRoute: typeof AuthenticatedManageShopIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync-places': {
      id: '/api/public/sync-places'
      path: '/api/public/sync-places'
      fullPath: '/api/public/sync-places'
      preLoaderRoute: typeof ApiPublicSyncPlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedManageShopIdRoute: typeof AuthenticatedManageShopIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedManageShopIdRoute: AuthenticatedManageShopIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GuideRoute: GuideRoute,
  OwnersRoute: OwnersRoute,
  ShopsShopSlugRoute: ShopsShopSlugRoute,
  ApiPublicSyncPlacesRoute: ApiPublicSyncPlacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
